# Dependencies
markdown:     redcarpet
highlighter:  null
layout:       null

# Permalinks
permalink:    pretty

# Setup
title:        indexcosmos blog
tagline:      'Make something great!'
description:  'A new blog powered with <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:          http://indexcosmos.github.io/
baseurl:      /
author:
  github:    https://github.com/indescosmos
  twitter:   https://twitter.com/saveabee
  linkedin:  https://www.linkedin.com/in/kimberlydrzewicki
paginate:     1

# Deploy settings
safe:         false
username:     'indescosmos'
destination:  '_site'

# Custom vars
version:      2.0.0
github:
  repo:       https://github.com/indexcosmos/indexcosmos.github.io
  exclude:    [ 'Gemfile', 'Gemfile.lock', 'Procfile', 'vendor', 'gems']
