# Dependencies
<<<<<<< HEAD

markdown:         kramdown
highlighter:      null
layout:           null

# Extensions
redcarpet: 
extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
=======
markdown:         redcarpet
highlighter:      null
layout:           null
>>>>>>> 6ea290faa22042dae9c8a31f09cc6ad7d6f2dd06

# Permalinks
permalink:        pretty

# Setup
title:            indexcosmos blog
tagline:          'Make something great!'
<<<<<<< HEAD
description:      'A new blog powered with <a href="http://jekyllrb.com" target="_blank">Jekyll</a> and layon theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
=======
description:      'A new blog powered with <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
>>>>>>> 6ea290faa22042dae9c8a31f09cc6ad7d6f2dd06
url:              http://indexcosmos.github.io/

author:
  name:           'Kimberly Drzewicki'
  url:            http://indexcosmos.github.io/

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/indexcosmos/indexcosmos.github.io
<<<<<<< HEAD
  exclude:  [ 'Gemfile', 'Gemfile.lock', 'Procfile', 'vendor', 'gems']
=======
>>>>>>> 6ea290faa22042dae9c8a31f09cc6ad7d6f2dd06
