# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A new blog provided through Github to rant and rave about the technology I work with.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://indexcosmos.github.io/" # the base hostname & protocol for your site
twitter_username: @saveabee
github_username:  indexcosmos

# Build settings
markdown: kramdown
