# Site settings
title: indexcosmos save the world
email: kdrewdesigns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog for technology related topics. A record of my thoughts on developing.
baseurl: "https://indexcosmos.github.io/blog" # the subpath of your site, e.g. /blog/
url: "https://indexcosmos.github.io" # the base hostname & protocol for your site
twitter_username: saveabee
github_username:  indexcosmos
timezone: America/New_York
# Build settings
markdown: kramdown
